import { AvailableClinicianScreen } from "../screens/appointment/AvailableClinicianScreen";

export default {

  HomeScreen: "HomeScreen",
  //Tabs
  HomeTab: "HomeTab",
  CalendarTab: "CalendarTab",
  MediaTab: "MediaTab",
  MessageTab: "MessageTab",
  ProfileTab: "ProfileTab",
  MenuTab: "MenuTab",
  AppointmentsTab: "AppointmentsTab",
  LoginTab: "LoginTab",
  DoctorTab: "DoctorTab",

  // Screens
  CalendarScreen: "CalendarScreen",
  MediaScreen: "MediaScreen",
  MediaDetailScreen: "MediaDetailScreen",
  MenuScreen: "MenuScreen",
  ProfileScreen: "ProfileScreen",
  EventListScreen: "EventListScreen",
  CampaignListScreen: "CampaignListScreen",
  CampaignDetailScreen: "CampaignDetailScreen",
  DepartmentListScreen: "DepartmentListScreen",
  DepartmentDetailScreen: "DepartmentDetailScreen",
  NewAppointmentScreen: "NewAppointmentScreen",
  DoctorListScreen: "DoctorListScreen",
  DoctorDetailScreen: "DoctorDetailScreen",
  MemberProfileScreen: "MemberProfileScreen",
  EditProfileScreen: "EditProfileScreen",
  CreateAppointmentScreen: "CreateAppointmentScreen",
  AppointmentsScreen: "AppointmentsScreen",
  LoginScreen: "LoginScreen",
  RegisterScreen: "RegisterScreen",
  AppointmentScreen:"AppointmentScreen",
  InboxScreen:"InboxScreen",
  AvailableClinicianScreen : "AvailableClinicianScreen",
  ConfirmAppointmentScreen : "ConfirmAppointmentScreen",
  RegisterContScreen: "RegisterContScreen",
  VideoConferenceScreen : "VideoConferenceScreen", 
  PrescriptionsScreen : "PrescriptionsScreen",
  NewPrescriptionScreen : "NewPrescriptionScreen", 
  MemberSearchScreen : "MemberSearchScreen", 
  PrescriptionScreen : "PrescriptionScreen",

  NewReferralScreen : "NewReferralScreen",
  ReferralScreen : "ReferralScreen",
  ReferralsScreen : "ReferralsScreen",
  ProviderAvailabilityScreen:"ProviderAvailabilityScreen",
  ServiceCostScreen:"ServiceCostScreen",
  ProvidersListScreen:"ProvidersListScreen",
  ProviderDetailScreen:"ProviderDetailScreen",
  BankInfoScreen:"BankInfoScreen",
  HMOScreen:"HMOScreen",
  SettingsScreen:"SettingsScreen",
  FamilyIntakeScreen:"FamilyIntakeScreen",
  PrimaryCareScreen:"PrimaryCareScreen",
  ProgressNoteScreen:"ProgressNoteScreen",
  PsychiatricProgressScreen:"PsychiatricProgressScreen",
  PediatricEvaluationScreen:"PediatricEvaluationScreen"
};
